language: java
sudo: false
dist: trusty

matrix:
  include:
    - jdk: oraclejdk8
      addons: {apt: {packages: [oracle-java8-installer]}}
    - jdk: oraclejdk9
      before_install:
        - cd ~
        - wget http://download.java.net/java/jdk9/archive/174/binaries/jdk-9-ea+174_linux-x64_bin.tar.gz
        - tar -xzf jdk-9-ea+174_linux-x64_bin.tar.gz
        - export JAVA_HOME=~/jdk-9
        - PATH=$JAVA_HOME/bin:$PATH
        - cd -
      env:
        - JDK_JAVA_OPTIONS='--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED'

# Don't let Travis CI execute './gradlew assemble' by default
install:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew -version

script:
# Build in steps to avoid out of memory errors
  - ./gradlew spotlessCheck
  - ./gradlew build --scan -x :junit-platform-gradle-plugin:check -x :platform-tests:check
  - ./gradlew :junit-platform-gradle-plugin:check --scan
  - ./gradlew :platform-tests:check --scan
